Fix cmake compatibility warning
ata4/angrylion-rdp-plus pull request #153
Opened 2023-08-05 11:20 UTC by Rosalie241

This PR fixes the following:
```
Make Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

and it fixes the following compilation error by including `stdexcept` to `parallel.cpp`:
```
[ 45%] Building CXX object CMakeFiles/alp-core.dir/src/core/parallel.cpp.o
/home/rosalie/dev/angrylion-rdp-plus/angrylion-rdp-plus/src/core/parallel.cpp: In member function ‘void Parallel::run(std::function<void(unsigned int)>&&)’:
/home/rosalie/dev/angrylion-rdp-plus/angrylion-rdp-plus/src/core/parallel.cpp:73:24: error: ‘runtime_error’ is not a member of ‘std’
   73 |             throw std::runtime_error("Workers are exiting and no longer accept work");
      |                        ^~~~~~~~~~~~~
/home/rosalie/dev/angrylion-rdp-plus/angrylion-rdp-plus/src/core/parallel.cpp:11:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; did you forget to ‘#include <stdexcept>’?
   10 | #include <vector>
  +++ |+#include <stdexcept>
   11 | 
make[2]: *** [CMakeFiles/alp-core.dir/build.make:94: CMakeFiles/alp-core.dir/src/core/parallel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

2023-08-05 16:59 UTC, Jj0YzL5nvJ requested changes
Weird, is `3.22` < `3.5`?
 Then, re-add: https://github.com/ata4/angrylion-rdp-plus/commit/c24268bddd44bcbb7f7d7f91b51dd30a6a92566b#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL31-L39

2023-08-05 17:21 UTC, GhostlyDark commented
`3.9` should be the minimum, as the checks for `cmake_policy(SET CMP0069 NEW)` have been removed. There is no need to go all the way up to `3.22`.

2023-08-05 20:31 UTC, Rosalie241 commented
> `3.9` should be the minimum, as the checks for `cmake_policy(SET CMP0069 NEW)` have been removed. There is no need to go all the way up to `3.22`.

Thank you, pushed it

2023-08-15 18:28 UTC, merged

2023-08-15 18:28 UTC, ata4 commented
Looks good, thank you for the improvements!